inputs:
  nord:
    port: IAC Driver IAC Bus 1

outputs:
  mixer:
    port: IAC Driver IAC Bus 2
    channel: 2 # TODO: CHANGE
  nord:
    port: IAC Driver IAC Bus 2
    channel: 1
    programFormat: nord
  prophet:
    port: IAC Driver IAC Bus 2
    channel: 10
    programFormat: prophet6
  juno:
    port: IAC Driver IAC Bus 2
    channel: 11
    programFormat: juno
  sampler:
    port: IAC Driver IAC Bus 2
    channel: 16 # TODO: change
