inputs:
  nord:
    port: MIDISPORT 4x4 Port A
  footswitch:
    port: MIDISPORT 4x4 Port B

outputs:
  mixer:
    port: MIDISPORT 4x4 Port A
    channel: 2 # TODO: CHANGE
  nord:
    port: MIDISPORT 4x4 Port B
    channel: 1
    programFormat: nord
  prophet:
    port: MIDISPORT 4x4 Port B
    channel: 10
    programFormat: prophet6
  juno:
    port: MIDISPORT 4x4 Port C
    channel: 11
    programFormat: juno
  sampler:
    port: MIDISPORT 4x4 Port C
    channel: 16 # TODO: change
