psych:
  name: 'Psych'
  programs:
    mixer: 1
    nord: '1:1'
  scenes:
    - name: Intro/Verse # ideally this can trigger hold + notes :O
      programs:
        prophet: 134
    - name: Keyboard Solo
      programs:
        prophet: 135
    - name: Verse 2
      programs:
        prophet: 134
    - name: Breakdown/Outro
      programs:
        prophet: 134
feel an emotion:
  name: Feel an Emotion
  scenes:
    - name: 'Intro'
      programs:
        prophet: 134
        nord: '1:2'
    - name: 'Keyboard Solo'
      programs:
        prophet: 480
livin asleep:
  name: Livin Asleep
