psych:
  name: 'Psych'
  programs:
    mixer: 1
    nord: '1:1'
    juno: '4:2'
  scenes:
    -
      name: Arpeggiator
      programs:
        prophet: 134
    -
      name: Keyboard Solo
      programs:
        prophet: 135
    -
      name: Arpeggiator
      programs:
        prophet: 134
    -
      name: Outro Pad
      programs:
        prophet: 136

feel an emotion:
  name: Feel an Emotion
  programs:
    mixer: 2
    nord: '1:2'

city escape:
  name: City Escape
  programs:
    mixer: 3
    nord: '1:3'
  scenes:
    -
      name: Ambient
      programs:
        prophet: 45
    -
      name: Shots
      programs:
        prophet: 48
    -
      name: Bridge
      programs:
        prophet: 47
    -
      name: Shots
      programs:
        prophet: 48

catacombs:
  name: Catacombs
  programs:
    mixer: 4
    nord: '1:4'
    prophet: 43

quarters:
  name: Quarters
  programs:
    mixer: 5
    nord: '1:5'
    juno: '4:1'

shadow:
  name: Shadow
  programs:
    mixer: 6
    nord: '1:6'
  scenes:
    -
      name: Ambient
      programs:
        prophet: 320
    -
      name: Phaser
      programs:
        prophet: 322
    -
      name: Ambient
      programs:
        prophet: 320
    -
      name: Phaser
      programs:
        prophet: 322
    -
      name: Solo Saw
      programs:
        prophet: 325

trails:
  name: Trails
  programs:
    mixer: 7
    nord: '2:1'
    prophet: 406

livin asleep:
  name: Livin Asleep
  programs:
    mixer: 8
    nord: '2:2'
    prophet: 415
    juno: '3:5'

mindmaker:
  name: Mindmaker
  programs:
    mixer: 9
    nord: '2:3'
    prophet: 117

elegy:
  name: Elegy
  programs:
    mixer: 10
    nord: '2:4'
    prophet: 9

strange dreams:
  name: Strange Dreams
  programs:
    mixer: 11
    nord: '2:5'

my days are numbered:
  name: My Days Are Numbered
  programs:
    mixer: 12
    nord: '2:6'
