psych:
  name: 'Psych'
  scenes:
    - name: Intro
      programs:
        mixer: 1
        prophet: 136
        nord: '1:1'
        juno: 6
    - name: Keyboard Solo
      programs:
        prophet: 135
feel an emotion:
  name: Feel an Emotion
  scenes:
    - name: 'Intro'
      programs:
        prophet: 134
        nord: '1:2'
        juno: 6
    - name: 'Keyboard Solo'
      programs:
        prophet: 135
livin asleep:
  name: Livin Asleep
